language: scala

install: true

cache:
  directories:
    - $HOME/.ivy2/cache
    - /tmp/texlive
    - $HOME/.texlive
    - $HOME/.cache/coursier
    - $HOME/.sbt

jobs:
  include:
    # Build with Linux systems.
    - stage: Run sbt on Linux
      os: linux
      dist: trusty
      scala:
        - 2.10.7
      jdk:
        - openjdk11
    - os: linux
      dist: trusty
      scala:
        - 2.12.12
      jdk:
        - openjdk11
    - os: linux
      dist: trusty
      scala:
        - 2.10.3
      jdk:
        - openjdk14
    - os: linux
      dist: trusty
      scala:
        - 2.12.12
      jdk:
        - openjdk14
    - os: linux
      dist: xenial
      scala:
        - 2.10.7
      jdk:
        - openjdk11
    - os: linux
      dist: xenial
      scala:
        - 2.12.12
      jdk:
        - openjdk11
    - os: linux
      dist: xenial
      scala:
        - 2.10.7
      jdk:
        - openjdk14
    - os: linux
      dist: xenial
      scala:
        - 2.12.12
      jdk:
        - openjdk14
    # Build with MacOs systems.
    - stage: Run sbt on Mac
      os: osx
      osx_image:
        - xcode12
      scala:
        - 2.10.7
      jdk:
        - openjdk14
    - os: osx
      osx_image:
        - xcode12
      scala:
        - 2.10.7
      jdk:
        - openjdk11
    - os: osx
      osx_image:
        - xcode12
      scala:
        - 2.12.12
      jdk:
        - openjdk14
    - os: osx
      osx_image:
        - xcode12
      scala:
        - 2.12.12
      jdk:
        - openjdk11
    - os: osx
      osx_image:
        - xcode11
      scala:
        - 2.10.7
      jdk:
        - openjdk14
    - os: osx
      osx_image:
        - xcode11
      scala:
        - 2.10.7
      jdk:
        - openjdk11
    - os: osx
      osx_image:
        - xcode11
      scala:
        - 2.12.12
      jdk:
        - openjdk14
    - os: osx
      osx_image:
        - xcode11
      scala:
        - 2.12.12
      jdk:
        - openjdk11
    # Send test statistics to other services.
    - stage: Deploys
      scala:
        - 2.12.12
      jdk: openjdk11
      os: linux
      dist: xenial
      script:
        - sbt coverage test coverageReport coverageAggregate doc
        # - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./target/scala-2.12/coverage-report/coberatura.xml
      before_deploy:
        - mkdir public
        - cp
      deploy:
        provider: pages
        strategy: git
        skip_cleanup: true
        token: $GH_TOKEN
        keep_history: true
        local_dir: public
        on:
          all_branches: true
        after_success:
          - bash <(curl -s https://codecov.io/bash)
    - stage: Deploys
      script:
        # Set up git user name and tag this commit.
        - git config --local user.name "Daniele Tentoni"
        - git config --local user.email "daniele.tentoni.1996@gmail.com"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
        - sbt clean packArchive
      deploy:
        provider: releases
        skip_cleanup: true
        token: $GH_TOKEN
        file_glob: true
        file:
          - /**/client-*.tar.gz
          - /**/client-*.zip
          - /**/server-*.tar.gz
          - /**/server-*.zip
        on:
          tags: true

stages:
  - name: Run sbt on Linux
    if: type = pull_request && !(branch = master)
  - name: Run sbt on Mac
    if: type = pull_request && !(branch = master)
  - name: Deploys
    if: type IN (pull_request, push) && branch = master
